Remove Team field from RequestedReviewer (#31)
This was causing a crash for me. The `name` field is missing from `Team` even though it's mentioned in the GraphQL API:
https://docs.github.com/en/graphql/reference/unions#requestedreviewer
https://docs.github.com/en/graphql/reference/objects#team

```
❯ jj-vine submit -r ok::
Submitting bookmarks: ***, ***, ***, ***
Error: GitHub API error: Failed to parse GraphQL response: missing field `name` at line 1 column 955, response: {"data":{"repository":{"pullRequests":{"nodes":[{"number":8330,"databaseId":3612543704,"title":"***","body":"***","headRefName":"***","headRepository":{"nameWithOwner":"***/***"},"headRefOid":"***","baseRefName":"***","baseRepository":{"nameWithOwner":"***/***"},"baseRefOid":"***","state":"OPEN","url":"https://github.com/***/***/pull/8330","isDraft":false,"merged":false,"createdAt":"2026-05-01T02:42:45Z","author":{"login":"ajhall"},"assignees":{"nodes":[]},"reviewRequests":{"nodes":[{"requestedReviewer":{"__typename":"Team"}}]}}]}}}}

Backtrace:
   0: snafu::backtrace_impl::<impl snafu::GenerateImplicitData for std::backtrace::Backtrace>::generate
   1: jj_vine::error::GitHubApiSnafu<__T0>::build
   2: <jj_vine::forge::github::GitHubForge as jj_vine::forge::Forge>::find_merge_request_by_source_branch::{{closure}}
   3: <jj_vine::forge::ForgeImpl as jj_vine::forge::Forge>::find_merge_request_by_source_branch_base_branch::{{closure}}
   4: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
   5: <futures_util::stream::stream::collect::Collect<St,C> as core::future::future::Future>::poll
   6: jj_vine::submit::plan::plan::{{closure}}
   7: jj_vine::commands::submit::submit::{{closure}}
   8: tokio::runtime::park::CachedParkThread::block_on
   9: jj_vine::main
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: main
  14: __libc_start_call_main
  15: __libc_start_main@@GLIBC_2.34
  16: _start
```

The `Team` field seems to be unused in the code, so I removed it and it worked fine. Let me know if you think this might break something, but from what I can tell it seems safe.

Reviewed-on: https://codeberg.org/abrenneke/jj-vine/pulls/31
Reviewed-by: Andy Brenneke <andy.brenneke@gmail.com>